version: "latest"

services:
  app:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
    healthcheck:
      test: "curl -f http:/localhost:8000/heartbeat/readiness || exit 1"
      interval: 20s
      retries: 5
      timeout: 3s
    volumes:
      - ./..:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ns

  mysql:
    build:
      context: ./..
      dockerfile: ./docker/mysql/Dockerfile
    restart: always
    volumes:
      - ./../docker/mysql/fixtures:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysql -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} $${MYSQL_DATABASE} -e 'select 1'"
      interval: 1s
      timeout: 15s
      retries: 15
    networks:
      - ns

networks:
  ns:
    driver: bridge