version: "3.8"

services:
  mysql:
    build:
      context: ./..
      dockerfile: ./docker/mysql2/Dockerfile
    container_name: mysql_service
    ports:
      - "3307:3306" # 将容器端口3306映射到主机端口3307
    volumes:
      - ./../docker/mysql2/fixtures:/docker-entrypoint-initdb.d # 数据库持久化存储
    command: ["mysqld", "--lower_case_table_names=1"] # 配置大小写不敏感
    restart: always                 # 容器崩溃后自动重启
    healthcheck:
      test: "mysql -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} $${MYSQL_DATABASE} -e 'select 1'"
      interval: 1s
      timeout: 15s
      retries: 15
    networks:
      - db_network

networks:
  db_network:
    driver: bridge